public class sepB extends sepA  {
    public static void insertcon(ID acid)			//method 2 insert contact
    {
        //sepB.insertacc();
        sepB xy = new sepB();
       // xy.insertacc();
        system.debug('acid in con:'+acid);
        
    /*    system.debug('id inside contact:'+acid);		
        List <Contact> conlist = new list <contact>();	//Empty List
        for (integer i=0;i<3;i++)						//create 3 contacts
        {
        contact con =new contact();		//object creation
        con.AccountId= acid;		//passing ID of account to contact 'Account Name'
        con.LastName='Yadav'+i;
        con.Phone='778844554'+i;
        con.Email='nil@kagde.com';
        
        conlist.add(con);			//adding con object into empty list
        }
        insert conlist;				//insert conlists
        system.debug('inserted contact list:'+conlist);   */
    }
}